# Generated by Django 3.1.4 on 2021-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('simple', models.BooleanField(default=True)),
                ('hard', models.BooleanField(default=True)),
                ('very_hard', models.BooleanField(default=True)),
            ],
        ),
    ]
