# Generated by Django 3.1.4 on 2021-01-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rec', '0005_question_subj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Ans',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='simple',
            new_name='easy',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='very_hard',
            new_name='medium',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Que',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Subj',
            new_name='subj',
        ),
    ]
